### PR TITLE
[NVIDIA] Add FP8 tutorial using TransformerEngine

### PR DESCRIPTION
**Pull request by ksivaman**

### CODE REVIEW

**Comment by bgchun** [comment]
@ksivaman Thank you for the PR! I noticed that for license information we have to check LICENSE. Could you add license information directly to main.py?

**Comment by ksivaman** [comment]
The full LICENSE file?

**Review by ktaebum — CHANGES_REQUESTED** [review]
Thank you for contributing the awesome example on Hopper GPUs!

I have left two minor comments that make the script executable when launching without TransformerEngine (i.e., just `python main.py`)

**Comment by bgchun** [comment]
> The full LICENSE file?

It'd be great if we can include a header of permissible license like AL2.

**Review by ktaebum — APPROVED** [review]

**Pull request merged**
